import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

describe("Apontamento Manual", () => {
  it("classifica Apontador e Manual, restringe a máquinas Processo Manual e inicia produção sem setup", () => {
    const proxySource = readFileSync(resolve(process.cwd(), "local-firebird-proxy/server.mjs"), "utf8");
    const contractSource = readFileSync(resolve(process.cwd(), "server/firebirdProxy.ts"), "utf8");
    const routerSource = readFileSync(resolve(process.cwd(), "server/routers/production.ts"), "utf8");
    const programmingSource = readFileSync(resolve(process.cwd(), "client/src/pages/Programming.tsx"), "utf8");
    const manualSource = readFileSync(resolve(process.cwd(), "client/src/pages/ManualPointing.tsx"), "utf8");
    const sessionSource = readFileSync(resolve(process.cwd(), "server/localSession.ts"), "utf8");
    const layoutSource = readFileSync(resolve(process.cwd(), "client/src/components/DashboardLayout.tsx"), "utf8");
    const themeSource = readFileSync(resolve(process.cwd(), "client/src/index.css"), "utf8");
    const reservationSource = readFileSync(resolve(process.cwd(), "client/src/components/ProductReservationDialog.tsx"), "utf8");
    const releaseSource = readFileSync(resolve(process.cwd(), "client/src/pages/ProductReleasePointing.tsx"), "utf8");
    const releaseRpncSource = readFileSync(resolve(process.cwd(), "client/src/components/ProductReleaseRpncDialog.tsx"), "utf8");

    expect(proxySource).toContain('gu.gu_usuario as group_description');
    expect(proxySource).toContain('normalizedDescription === "APONTADOR"');
    expect(proxySource).toContain('description.includes("APONTAMENTO")');
    expect(proxySource).toContain("Boolean(machine?.manualProcess)");
    expect(proxySource).toContain('left join funcionarios fun');
    expect(proxySource).toContain('left join grupo_usuarios gu');
    expect(proxySource).toContain('normalizedDescription === "MANUAL"');
    expect(proxySource).toContain('manual-production');
    expect(proxySource).toContain('máquinas marcadas como Processo Manual');
    expect(proxySource).toContain('const logonCandidates = [...new Set([configuredLogon, localHostname]');
    expect(proxySource).toContain('for (const logonName of logonCandidates)');
    expect(proxySource).toContain('app.post("/v1/pointing/:opCodigo/:mpCodigo/start-manual"');
    expect(proxySource).toContain("mp_status = 'Em Produção'");
    expect(proxySource).toContain("['Liberado', 'Aberto', 'Parcial']");
    expect(proxySource).not.toContain('Somente a fila 1 pode iniciar o apontamento manual.');
    expect(proxySource).toContain('O Apontamento Manual só pode ser iniciado em máquina marcada como Processo Manual.');
    expect(contractSource).toContain('operationalProfile: "operator" | "programmer" | "manual-pointing" | "manual-production" | "quality-release"');
    expect(contractSource).toContain('quantityPeople: number');
    expect(contractSource).toContain('productionDate: string');
    expect(contractSource).toContain("export const startManualPointing");
    expect(routerSource).toContain("startManual: operatorProcedure");
    const localAuthSource = readFileSync(resolve(process.cwd(), "server/routers/localAuth.ts"), "utf8");
    expect(localAuthSource).toContain("stationAccessDenied");
    expect(localAuthSource).toContain("Processo Manual");
    expect(programmingSource).toContain("/apontamento-manual/");
    expect(programmingSource).toContain('const manualEligible = ["Liberado", "Parcial", "Em Produção"]');
    expect(programmingSource).toContain('const operationalStatusFilter = manualPointing || coladeiraMachine ? statusFilter : operator ? "Todos" : statusFilter');
    expect(programmingSource).toContain('processSequence.data?.length ? <div className="flex gap-2 overflow-x-auto');
    expect(programmingSource).toContain('if ((manualPointing || coladeiraMachine) && !OPERATIONAL_STATUS_FILTER_OPTIONS.includes(statusFilter)) setStatusFilter("Liberado")');
    expect(programmingSource).toContain('processSequence.data?.length ? <div className="flex gap-2 overflow-x-auto');
    expect(programmingSource).toContain('enabled: Boolean(user?.machine) && operator && !manualPointing');
    expect(sessionSource).toContain('payload.operationalProfile === "programmer" || payload.operationalProfile === "manual-pointing" || payload.operationalProfile === "manual-production" || payload.operationalProfile === "quality-release"');
    expect(programmingSource).toContain('["manual-pointing", "manual-production", "quality-release"]');
    expect(programmingSource).toContain('manualPointing ? "Ordens para apontamento" : "Fila operacional"');
    expect(programmingSource).toContain('selectedItem ? <section className="theme-details-panel');
    expect(programmingSource).toContain('!manualPointing ? <><SortableHeader label="Situação M.P."');
    expect(programmingSource).toContain('onClick={manualPointing ? signOut : operator ? () => setShowExitOptions(true) : signOut}');
    expect(manualSource).toContain("Apontamento Manual");
    expect(manualSource).toContain('label="Quantidade produzida"');
    expect(manualSource).toContain('label="Quantidade perdida"');
    expect(manualSource).toContain('label="Quantidade de pessoas"');
    expect(manualSource).toContain("Quantidades produzidas anteriores");
    expect(manualSource).toContain("Atendido");
    expect(manualSource).toContain("Parcial");
    expect(manualSource).toContain("Voltar");
    expect(manualSource).toContain("manual-quantity-input");
    expect(manualSource).toContain("const requiresPeople = user?.operationalProfile === \"manual-production\"");
    expect(manualSource).toContain('Data de produção');
    expect(manualSource).toContain('type="date"');
    expect(manualSource).toContain('Confirmar data de produção');
    expect(manualSource).toContain('dateConfirmationKind');
    expect(manualSource).toContain('Quantidade a apontar');
    expect(manualSource).toContain('quantityDeviation');
    expect(manualSource).toContain('Quantidade diferente do processo anterior');
    expect(routerSource).toContain('input.quantityPeople < 1');
    expect(proxySource).toContain('mph_qtde_fun = ?');
    expect(proxySource).toContain('pvpp_baixar_estoque');
    expect(proxySource).toContain('update ordens_producao set op_produzido');
    expect(proxySource).toContain('finishedGoodsQuantity');
    expect(proxySource).toContain('function isPointingMachineGroup');
    expect(proxySource).toContain('pointingGroup && finishedGoodsQuantity > 0');
    expect(proxySource).toContain('select first 1 mph.mph_data as production_date from mov_processos_horarios mph inner join maquinas_processos mq on mq.mqp_codigo = mph.mqp_codigo where mph.op_codigo = ? and mq.gmq_codigo <> 1 order by mph.mph_codigo');
    expect(proxySource).toContain('new Date().toISOString().slice(0, 10)');
    expect(proxySource).not.toContain('coalesce(first_mp.mp_data');
    expect(proxySource).toContain('mv.mp_qtdeapontada as previous_quantity');
    expect(proxySource).toContain('previous_process_balance');
    expect(proxySource).toContain('mv.mp_codigo < ? and mv.mp_qtdeapontada > 0 order by mv.mp_codigo desc');
    expect(proxySource).toContain('op_ant.previous_quantity - coalesce(current_process.mp_qtdeapontada, 0)');
    expect(manualSource).toContain('large ? "h-32 text-7xl"');
    expect(layoutSource).toContain('["manual-pointing", "manual-production", "quality-release"]');
    expect(layoutSource).toContain("operatorStation || programmerStation || manualPointingStation");
    expect(themeSource).toContain(".manual-pointing-header");
    expect(themeSource).toContain(".manual-quantity-input");
    expect(themeSource).toContain("font-size: 5rem !important");
    expect(themeSource).toContain('.manual-production-date');
    expect(themeSource).toContain('.reservation-dialog');
    expect(reservationSource).toContain('header("Quantidade", "quantity", "text-right")');
    expect(reservationSource).toContain('reservation-quantity');
    expect(proxySource).toContain('product-release-plan');
    expect(proxySource).toContain('plano_amostragem');
    expect(proxySource).toContain('mph_situacao_lib');
    expect(releaseSource).toContain('Nível de Inspeção Geral II');
    expect(releaseSource).toContain('Não Conforme');
    expect(releaseSource).toContain('Amostragem Geral');
    expect(releaseSource).toContain('Saldo a liberar');
    expect(releaseSource).not.toContain('Quantidade recebida');
    expect(releaseRpncSource).toContain('"Confirmar"');
    expect(releaseRpncSource).toContain('Causa aparente');
    expect(manualSource).toContain('ProductReleaseRpncDialog');
    expect(releaseRpncSource).toContain('transitionToGeneralSampling');
    expect(releaseSource).toContain('A liberação Conforme não se aplica nesta etapa.');
    expect(proxySource).toContain("mp.mp_situacao_lib as release_situation");
    expect(releaseSource).toContain("returnedFromRpnc");
    expect(releaseSource).toContain('setLocation("/")');
    expect(proxySource).toContain("Foram encontrados horários ativos duplicados");
    expect(proxySource).toContain("activeScheduleRows");
    expect(manualSource).toContain("manualStartKeyRef");
    expect(releaseSource).toContain("releaseStartKeyRef");
    expect(releaseSource).toContain("generalSampling ? \"Não Conforme\" : conformity");
    expect(proxySource).toContain("with lock");
    expect(releaseSource).toContain('Saldo a liberar');
    expect(releaseSource).toContain('generalSampling ? <div');
  });
});
