import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

describe("Apontamento Manual", () => {
  it("classifica Apontador por GU_USUARIO, restringe a máquina Apontamento e inicia produção sem setup", () => {
    const proxySource = readFileSync(resolve(process.cwd(), "local-firebird-proxy/server.mjs"), "utf8");
    const contractSource = readFileSync(resolve(process.cwd(), "server/firebirdProxy.ts"), "utf8");
    const routerSource = readFileSync(resolve(process.cwd(), "server/routers/production.ts"), "utf8");
    const programmingSource = readFileSync(resolve(process.cwd(), "client/src/pages/Programming.tsx"), "utf8");
    const manualSource = readFileSync(resolve(process.cwd(), "client/src/pages/ManualPointing.tsx"), "utf8");
    const sessionSource = readFileSync(resolve(process.cwd(), "server/localSession.ts"), "utf8");
    const layoutSource = readFileSync(resolve(process.cwd(), "client/src/components/DashboardLayout.tsx"), "utf8");
    const themeSource = readFileSync(resolve(process.cwd(), "client/src/index.css"), "utf8");

    expect(proxySource).toContain('gu.gu_usuario as group_description');
    expect(proxySource).toContain('normalizedDescription === "APONTADOR"');
    expect(proxySource).toContain('description.includes("APONTAMENTO")');
    expect(proxySource).toContain("Boolean(machine?.manualProcess)");
    expect(proxySource).toContain('left join funcionarios fun');
    expect(proxySource).toContain('left join grupo_usuarios gu');
    expect(proxySource).toContain('O usuário Apontador só pode acessar a máquina Apontamento.');
    expect(proxySource).toContain('A máquina Apontamento é exclusiva para usuários Apontador.');
    expect(proxySource).toContain('const logonCandidates = [...new Set([configuredLogon, localHostname]');
    expect(proxySource).toContain('for (const logonName of logonCandidates)');
    expect(proxySource).toContain('app.post("/v1/pointing/:opCodigo/:mpCodigo/start-manual"');
    expect(proxySource).toContain("mp_status = 'Em Produção'");
    expect(proxySource).not.toContain('Somente a fila 1 pode iniciar o apontamento manual.');
    expect(proxySource).toContain('O Apontamento Manual só pode ser iniciado na máquina Apontamento.');
    expect(contractSource).toContain('operationalProfile: "operator" | "programmer" | "manual-pointing"');
    expect(contractSource).toContain("export const startManualPointing");
    expect(routerSource).toContain("startManual: operatorProcedure");
    const localAuthSource = readFileSync(resolve(process.cwd(), "server/routers/localAuth.ts"), "utf8");
    expect(localAuthSource).toContain("stationAccessDenied");
    expect(localAuthSource).toContain("máquina Apontamento");
    expect(programmingSource).toContain("/apontamento-manual/");
    expect(programmingSource).toContain('const manualEligible = ["Liberado", "Parcial", "Em Produção"]');
    expect(programmingSource).toContain('status: manualPointing ? "Liberado/Parcial/Em Produção" : operator ? "Todos" : statusFilter');
    expect(programmingSource).toContain('processSequence.data?.length ? <div className="flex gap-2 overflow-x-auto');
    expect(programmingSource).toContain('status: manualPointing ? "Liberado/Parcial/Em Produção" : operator ? "Todos" : statusFilter');
    expect(programmingSource).toContain('processSequence.data?.length ? <div className="flex gap-2 overflow-x-auto');
    expect(programmingSource).toContain('enabled: Boolean(user?.machine) && operator && !manualPointing');
    expect(sessionSource).toContain('payload.operationalProfile === "programmer" || payload.operationalProfile === "manual-pointing"');
    expect(programmingSource).toContain('manualPointing ? "Ordens para apontamento" : "Fila operacional"');
    expect(programmingSource).toContain('selectedItem ? <section className="theme-details-panel');
    expect(programmingSource).toContain('!manualPointing ? <><th className="px-3 py-3">Situação M.P.</th><th className="px-3 py-3">Solicitação</th></> : null');
    expect(programmingSource).toContain('onClick={manualPointing ? signOut : operator ? () => setShowExitOptions(true) : signOut}');
    expect(manualSource).toContain("Apontamento Manual");
    expect(manualSource).toContain("Qtde. produzida");
    expect(manualSource).toContain("Quantidades produzidas anteriores");
    expect(manualSource).toContain("Atendido");
    expect(manualSource).toContain("Parcial");
    expect(manualSource).toContain("Voltar");
    expect(manualSource).toContain("manual-quantity-input");
    expect(manualSource).not.toContain("peopleCount");
    expect(manualSource).not.toContain("Pessoas");
    expect(manualSource).toContain("h-32 border-2 text-center font-mono text-7xl");
    expect(manualSource).toContain('large ? "h-32 text-7xl"');
    expect(layoutSource).toContain('const manualPointingStation = user?.operationalProfile === "manual-pointing"');
    expect(layoutSource).toContain("operatorStation || programmerStation || manualPointingStation");
    expect(themeSource).toContain(".manual-pointing-header");
    expect(themeSource).toContain(".manual-quantity-input");
    expect(themeSource).toContain("font-size: 5rem !important");
  });
});
