import { StatusPill } from "@/components/ProductionPrimitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { BarChart3 } from "lucide-react";

type ApprovedProcessQuantity = { processGroup: number | null; arrangement: string | null; approvedQuantity: number | null; status: string | null };

export function ApprovedProcessQuantitiesDialog({ open, onOpenChange, data, loading, error }: { open: boolean; onOpenChange: (open: boolean) => void; data: ApprovedProcessQuantity[] | undefined; loading: boolean; error: { message: string } | null }) {
  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="!flex !w-[calc(100vw-1rem)] !max-w-4xl !flex-col !overflow-hidden border-2 border-[#d5b85f] bg-[#fffdf6] p-0 shadow-2xl sm:!w-[calc(100vw-2rem)]">
      <DialogHeader className="border-b-2 border-[#ead69c] bg-gradient-to-r from-[#fff6d9] via-[#f5fbf3] to-white px-5 py-4 sm:px-6"><DialogTitle className="flex items-center gap-2 text-2xl font-black text-[#3f513a]"><BarChart3 className="h-6 w-6 text-[#b88014]" />Quantidades aprovadas</DialogTitle><DialogDescription className="mt-1 text-sm font-bold text-[#697a67]">Histórico consolidado da OP por grupo de processo, arranjo e situação.</DialogDescription></DialogHeader>
      <div className="w-full bg-[#fffdf6] p-4 sm:p-6">{loading ? <p className="rounded-xl bg-[#f4f8f1] p-5 text-base font-bold text-[#52705a]">Consultando quantidades aprovadas…</p> : error ? <p className="rounded-xl border-2 border-[#e3abab] bg-[#fff2f2] p-5 text-base font-bold text-[#a23434]">{error.message}</p> : !data?.length ? <p className="rounded-xl border-2 border-dashed border-[#d8c783] bg-white p-6 text-center text-base font-bold text-[#7a6937]">Ainda não há quantidades aprovadas registradas para esta OP.</p> : <div className="w-full overflow-x-auto rounded-xl border-2 border-[#dfe7df] bg-white"><div className="min-w-[650px]"><div className="grid grid-cols-[1.1fr_1.2fr_1fr_1fr] border-b-2 border-[#e0c976] bg-[#fff2c9] px-4 py-3 font-mono text-xs font-black uppercase tracking-[.12em] text-[#705719]"><span>Processo</span><span>Arranjo</span><span className="text-right">Q. aprovada</span><span className="text-center">Status</span></div>{data.map((row, index) => <div key={`${row.processGroup}-${row.arrangement}-${row.status}-${index}`} className={`grid grid-cols-[1.1fr_1.2fr_1fr_1fr] items-center border-b border-[#edf0ea] px-4 py-3 ${index % 2 ? "bg-[#fbfdfb]" : "bg-white"}`}><span className="font-bold text-[#355044]">Grupo {row.processGroup ?? "—"}</span><span className="font-mono font-bold text-[#56685f]">{row.arrangement || "—"}</span><span className="text-right font-mono text-lg font-black text-[#177458]">{row.approvedQuantity ?? 0}</span><span className="justify-self-center"><StatusPill status={row.status} /></span></div>)}</div></div>}</div>
      <div className="flex w-full justify-end border-t border-[#e7ebdf] bg-[#fffdf6] px-5 py-4"><Button onClick={() => onOpenChange(false)} className="h-12 rounded-lg bg-[#cf3f3f] px-6 text-base font-black text-white hover:bg-[#ad2e2e]">Fechar</Button></div>
    </DialogContent>
  </Dialog>;
}
