import { ConnectionNotice, displayValue, LoadingRows, processStatusClass, SearchBar, StatusPill, TablePagination } from "@/components/ProductionPrimitives";
import { ProductPalletizationDialog, ProductPrintLayoutDialog } from "@/components/ProductVisualDialogs";
import { ProductReservationDialog } from "@/components/ProductReservationDialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useLocalAuth } from "@/hooks/useLocalAuth";
import { trpc } from "@/lib/trpc";
import { FileImage, Layers3, Package, PackageSearch, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";

function date(value: string | null) { return value ? (Number.isNaN(new Date(value).valueOf()) ? value : new Date(value).toLocaleDateString("pt-BR")) : "—"; }
function color(hex: string | null | undefined) { return /^#[0-9a-fA-F]{6}$/.test(hex ?? "") ? hex! : "#176148"; }

export function QueueConsultationDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { user } = useLocalAuth();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [selectedOpCode, setSelectedOpCode] = useState<number | null>(null);
  const [showReservations, setShowReservations] = useState(false);
  const [showPalletization, setShowPalletization] = useState(false);
  const [showPrintLayout, setShowPrintLayout] = useState(false);
  const queue = trpc.production.queue.list.useQuery({ page, limit: 20, search }, { enabled: open, retry: false });
  const selected = queue.data?.items.find((item) => item.opCode === selectedOpCode) ?? queue.data?.items[0] ?? null;
  const reservations = trpc.production.queue.reservations.useQuery({ opCode: selected?.opCode ?? 0 }, { enabled: showReservations && Boolean(selected), retry: false });
  const processes = trpc.production.queue.processes.useQuery({ opCode: selected?.opCode ?? 0, masterOrder: selected?.masterOrder ?? null }, { enabled: open && Boolean(selected), retry: false });
  const palletization = trpc.production.pointing.palletization.useQuery({ opCodigo: selected?.opCode ?? 0, mpCodigo: selected?.mpCode ?? 0 }, { enabled: showPalletization && Boolean(selected), retry: false });
  const printLayout = trpc.production.pointing.printLayout.useQuery({ opCodigo: selected?.opCode ?? 0, mpCodigo: selected?.mpCode ?? 0 }, { enabled: Boolean(selected), retry: false });

  useEffect(() => { if (open) { setPage(1); setSearch(""); setSelectedOpCode(null); setShowReservations(false); setShowPalletization(false); setShowPrintLayout(false); } }, [open]);
  useEffect(() => { if (queue.data?.items.length && !queue.data.items.some((item) => item.opCode === selectedOpCode)) setSelectedOpCode(queue.data.items[0].opCode); }, [queue.data, selectedOpCode]);
  return <>
    <Dialog open={open} onOpenChange={(next) => { if (!next) onClose(); }}>
      <DialogContent className="max-h-[92dvh] !w-[calc(100vw-2rem)] !max-w-[1320px] overflow-hidden border border-slate-300 bg-[#fbfcfe] p-0 shadow-2xl">
        <DialogHeader className="border-b border-slate-200 bg-white px-5 py-4 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><DialogTitle className="flex items-center gap-2 text-2xl font-black text-slate-800"><Layers3 className="h-6 w-6 text-[#177458]" />Fila de programação</DialogTitle><DialogDescription className="mt-1 text-sm font-bold text-slate-500">Consulte a sequência liberada da máquina e os dados operacionais de cada OP.</DialogDescription></div><div className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-right"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Máquina</p><p className="mt-0.5 text-sm font-black text-slate-700">{user?.machine?.description ?? "Não identificada"}</p></div></div></DialogHeader>
        <div className="flex max-h-[calc(92dvh-175px)] flex-col overflow-hidden">
          <div className="flex flex-col gap-3 border-b border-slate-200 bg-slate-50 px-5 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-bold text-slate-600">A fila exibe os processos desta máquina com posição menor que 1000.</p><div className="flex gap-2"><SearchBar value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="OP, produto, referência ou cliente" /><Button variant="outline" onClick={() => queue.refetch()} className="h-10 border-slate-300 bg-white px-3 font-black text-slate-700"><RefreshCw className="mr-1.5 h-4 w-4" />Atualizar</Button></div></div>
          {selected ? <div className="border-b border-[#ead9ad] bg-[#fffaf0] px-5 py-3"><div className="flex flex-col gap-2 xl:flex-row xl:items-center"><p className="shrink-0 text-[10px] font-black uppercase tracking-[.12em] text-[#806c32]">Processos da OP</p><div className="flex min-w-0 gap-2 overflow-x-auto pb-1">{processes.isLoading ? <span className="text-sm font-bold text-slate-400">Carregando processos…</span> : processes.data?.map((process) => <div key={`${process.opCode}-${process.mpCode}`} className={`min-w-[180px] rounded-lg border border-slate-300 px-3 py-2 text-center shadow-sm ${processStatusClass(process.status)} ${process.mpCode === selected.mpCode ? "ring-2 ring-[#177458]/30" : ""}`}><p className="truncate text-sm font-black">{process.machineDescription}</p><p className="mt-0.5 text-xs font-bold">{process.status || "Sem status"}{process.queue != null ? ` · Fila ${process.queue}` : ""}</p></div>)}</div></div></div> : null}
          {queue.error ? <div className="px-5 pt-3"><ConnectionNotice error={queue.error} title="Não foi possível consultar a Fila da máquina" /></div> : null}
          <div className="min-h-0 flex-1 overflow-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead className="sticky top-0 z-10 bg-[#f8edcc] text-[10px] font-bold uppercase tracking-[.1em] text-[#796126]"><tr><th className="px-4 py-3 text-center">Fila</th><th className="px-4 py-3">OP</th><th className="px-4 py-3">Produto</th><th className="px-4 py-3">Referência / Cliente</th><th className="px-4 py-3 text-right">Qtde</th><th className="px-4 py-3">Data exp.</th><th className="px-4 py-3">Data ent.</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3">Reserva</th></tr></thead><tbody className="divide-y divide-slate-100">{queue.isLoading ? <LoadingRows columns={9} /> : queue.data?.items.map((item) => <tr key={`${item.opCode}-${item.mpCode}`} onClick={() => setSelectedOpCode(item.opCode)} className={`cursor-pointer transition-colors ${item.opCode === selected?.opCode ? "bg-[#edf7f1] shadow-[inset_3px_0_0_#177458]" : "bg-white hover:bg-[#fffaf0]"}`}><td className="px-4 py-3 text-center"><span className="rounded-md bg-slate-100 px-2 py-1 font-mono text-xs font-black text-slate-600">{displayValue(item.queue)}</span></td><td className="px-4 py-3 font-mono text-xs font-bold text-slate-700">{item.opCode}</td><td className="px-4 py-3 font-mono text-xs text-slate-500">{displayValue(item.productCode)}</td><td className="px-4 py-3"><p className="font-bold text-slate-700">{displayValue(item.reference)}</p><p className="mt-0.5 text-xs text-slate-400">{displayValue(item.customer)}</p></td><td className="px-4 py-3 text-right font-mono text-xs font-bold text-slate-700">{displayValue(item.quantity)}</td><td className="px-4 py-3 text-xs text-slate-500">{date(item.shipmentDate)}</td><td className="px-4 py-3 text-xs text-slate-500">{date(item.deliveryDate)}</td><td className="px-4 py-3"><StatusPill status={item.status} /></td><td className="px-4 py-3 text-xs font-bold text-slate-500">{displayValue(item.reservationRequestStatus || item.reservationStatus)}</td></tr>)}</tbody></table>{!queue.isLoading && !queue.data?.items.length ? <p className="px-5 py-12 text-center text-sm text-slate-400">Não há ordens em fila para esta máquina.</p> : null}</div>
          <TablePagination page={page} total={queue.data?.total ?? 0} limit={20} onChange={setPage} />
          <div className="border-t border-[#ead9ad] bg-[#fffaf0] px-5 py-3"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-center gap-2 overflow-x-auto"><span className="shrink-0 text-[10px] font-black uppercase tracking-[.12em] text-[#806c32]">Cores</span>{printLayout.data?.colors?.length ? printLayout.data.colors.map((item) => <span key={`${item.order}-${item.description}`} className="shrink-0 rounded-md border border-white/70 px-3 py-1.5 text-sm font-black text-white shadow-sm" style={{ backgroundColor: color(item.hexWhite) }}>{item.description}</span>) : <span className="text-sm font-bold text-slate-400">Sem cores cadastradas</span>}</div><div className="flex flex-wrap items-center gap-2 border-t border-[#ead9ad] pt-3 lg:border-l lg:border-t-0 lg:pl-4 lg:pt-0"><span className="text-[10px] font-black uppercase tracking-[.12em] text-[#806c32]">Ferramentais</span><span className="rounded-md border border-[#dec679] bg-white px-3 py-1.5 text-sm font-black text-[#665016]">Clichê: {printLayout.data?.cliches?.length ? printLayout.data.cliches.map((item) => `${item.code}${item.series ? `/${item.series}` : ""}`).join(" · ") : "—"}</span><span className="rounded-md border border-[#dec679] bg-white px-3 py-1.5 text-sm font-black text-[#665016]">Faca: {printLayout.data?.facas?.length ? printLayout.data.facas.map((item) => item.code).join(" · ") : "—"}</span></div></div></div>
          <div className="border-t border-slate-200 bg-white px-5 py-4"><div className="grid gap-3 lg:grid-cols-[auto_auto_1fr_auto_auto_auto_auto]"><div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">OP selecionada</p><p className="mt-1 font-mono text-lg font-black text-slate-700">{selected?.opCode ?? "—"}</p></div><div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Cores</p><p className="mt-1 font-mono text-lg font-black text-slate-700">{selected?.colorCount ?? 0}</p></div><div className="grid gap-1 rounded-lg border border-slate-200 bg-white px-3 py-2 sm:grid-cols-2"><p className="text-sm font-bold text-slate-600">Ajuste L: <span className="font-mono text-slate-800">{displayValue(selected?.adjustmentWidth)}</span></p><p className="text-sm font-bold text-slate-600">Ajuste C: <span className="font-mono text-slate-800">{displayValue(selected?.adjustmentLength)}</span></p></div><Button disabled={!selected} variant="outline" onClick={() => setShowReservations(true)} className="h-12 border-2 border-[#e0bd50] bg-[#fff9df] text-sm font-black text-[#705511]"><PackageSearch className="mr-2 h-4 w-4" />Reserva</Button><Button disabled={!selected} variant="outline" onClick={() => setShowPalletization(true)} className="h-12 border-2 border-slate-300 bg-white text-sm font-black text-slate-700"><Package className="mr-2 h-4 w-4 text-[#177458]" />Pacotes / Paletização</Button><Button disabled={!selected} variant="outline" onClick={() => setShowPrintLayout(true)} className="h-12 border-2 border-slate-300 bg-white text-sm font-black text-slate-700"><FileImage className="mr-2 h-4 w-4 text-[#177458]" />Visualizar layout</Button><Button variant="outline" onClick={onClose} className="h-12 rounded-lg border-2 border-[#cf3f3f] bg-[#cf3f3f] text-sm font-black text-white hover:bg-[#ad2e2e]">Fechar</Button></div></div>
        </div>
      </DialogContent>
    </Dialog>
    <ProductReservationDialog open={showReservations} onOpenChange={setShowReservations} opCode={selected?.opCode} data={reservations.data} loading={reservations.isLoading} error={reservations.error} />
    <ProductPalletizationDialog open={showPalletization} onOpenChange={setShowPalletization} data={palletization.data} loading={palletization.isLoading} error={palletization.error} productLabel={String(selected?.opCode ?? "")} />
    <ProductPrintLayoutDialog open={showPrintLayout} onOpenChange={setShowPrintLayout} data={printLayout.data} loading={printLayout.isLoading} error={printLayout.error} productLabel={selected?.productCode === undefined ? undefined : String(selected.productCode)} revision={selected?.revision} />
  </>;
}
